### ISSUE TITLE
The shortcut to the editor isn't working and the editor's interface looks kinda broken

### ISSUE THREAD

**Issue by LOuroboros** [M3rein/Pokemon-MK#2]
1) The shortcut to the editor that's in the Master folder ("Pokémon MK Engine") isn't working.
When I double click it, the mouse cursor goes into "Working in background" state like this:
![explorer_2017-12-05_19-54-45](https://user-images.githubusercontent.com/4485172/33636228-13ee28b8-d9fa-11e7-8832-f7a9aa02e194.png)

But nothing happens and I also can't spot anything out of the ordinary like a mkxp.exe process in my Task Manager or anything.

**EDIT**: However, if you make a shortcut manually to \Pokemon-Kit-master\Pokémon Engine\PokemonEngine\bin\Debug\PokemonEngine.exe, it does work correctly.

2) The editor's interface looks kinda broken.
I recorded a small video showing how it's looking right now on my PC which uses Windows 8.1 x64.
https://www.youtube.com/watch?v=k2ADhrOJEhU

**Comment by M3rein** [comment]
As for the shortcut — that’s something I thought was possible on different computers, but I guess not. I’ll take it out in the next commit.

As for the editor, it’s likely got to do with your monitor’s resolution. I haven’t made it work with all resolutions yet as I want to get it functional first. Could you tell me your screen resolution?

**Comment by LOuroboros** [comment]
Sure thing @M3rein, it's 1360x768.

**Comment by M3rein** [comment]
Ah yeah, I think the default resolution is just a bit bigger than that, which would explain the awkward display. I changed the way the map’s positioning worked earlier (to make room for a toolbar) which would also cause this issue. I don’t know when this’ll be fixed, but the toolbar should be up and running tomorrow or the day after.

**Comment by M3rein** [comment]
Added a task bar and the map tab now works with all screensizes.
