### ISSUE TITLE
Game.exe crashes upon pressing the X letter and PokémonEngine.exe still throws an error when you execute it

### ISSUE THREAD

**Issue by LOuroboros** [M3rein/Pokemon-MK#4]
1) When I open "Game.exe", if I press the X letter of my keyboard (_which I think worked as a "Load Savestate" kinda option before_), I get this crash:
![game_2017-12-07_20-08-03](https://user-images.githubusercontent.com/4485172/33743217-a6030ff2-db8a-11e7-9a32-d1c9ccf94dcc.png)

2) When I open "PokemonEngine.exe" I'm getting this crash:
![explorer_2017-12-07_20-13-45](https://user-images.githubusercontent.com/4485172/33743427-8e0d7e54-db8b-11e7-935e-bac89eb3016b.png)

Yes, I know, it's in Spanish. I grabbed what seemed to be the most relevant bit:
https://pastebin.com/raw/2rMGbbY8

After clicking the "Continue" button, I get a 2nd error:
![explorer_2017-12-07_20-21-04](https://user-images.githubusercontent.com/4485172/33743571-2e5996b8-db8c-11e7-9dc7-78e276607591.png)

Same as before, here's the relevant bit:
https://pastebin.com/raw/uuE4W3X4

After clicking the "Continue" button again, the tool opens but it doesn't show the tileset nor the test map:
![pokemonengine_2017-12-07_20-23-24](https://user-images.githubusercontent.com/4485172/33743649-80e2783c-db8c-11e7-97e8-01ca5d780028.png)

In this weird state, if I decide to minimize it, I get this error:
![pokemonengine_2017-12-07_20-23-53](https://user-images.githubusercontent.com/4485172/33743671-996d5958-db8c-11e7-8349-366f97e55f5e.png)

Same as before, here's the relevant bit:
https://pastebin.com/raw/6vPi0HrC

At that point I just closed the "PokemonEngine.exe" file and opened it again. 2 errors.
This time I clicked the "Exit" button and opened the tool again.
Now it's throwing me one single error and after clicking the "Continue" button the application seems to be opening correctly. It is still throwing me the same error than before when I minimize it though.

On top of that, if I click the "Play" button, this is what happens:
![pokemonengine_2017-12-07_20-27-58](https://user-images.githubusercontent.com/4485172/33743822-294f0ad0-db8d-11e7-91be-04a10a73da96.png)

And from that point onwards, I have to re-download the whole thing because Game.exe simply refuses to open, always throwing me the exact same error about the Scripts.rxdata file.

I'm starting to think that it's weird that I seem to be the only one getting these issues.
Maybe the whole thing uses some very specific vcredist library or some version of .NET Framework that I don't have..?
Or maybe some Windows 10 DLL or something? Because I have Windows 8.1 (_x64_), if that helps.

**Comment by M3rein** [comment]
1. This is actually intentional. I was testing with error messages and hadn’t taken this out yet.

2. Will be looked at.

Minimizing in that state does seem to be an actual bug, which will also be looked at.

I recommend never clicking “Continue”. Most of the time, it’ll do more harm than good. It probably overwrote some files and bugged it in the process. I’m pretty sure the rest of the mentioned issues are a result of that.

**Comment by M3rein** [comment]
These bugs should have been resolved.
