### ISSUE TITLE
Custom map looking good inside the Editor but wrong inside the Game

### ISSUE THREAD

**Issue by LOuroboros** [M3rein/Pokemon-MK#6]
So, after the Editor/Engine was fixed today and I was able to safely open it yet again, I decided to go ahead and practice a little bit my _no-existent_ mapping skills. I decided to start with something easy, remaking Pokémon FR/LG's main character's room.
I think that I did everything correctly. I used the Layers 1, 2, 3 and 4 and once I was satisfied with the result, I just clicked the "Save" button and tested the map In-Game.
Unfortunately, it looks quite messed up over there and I don't know why.
![pokemonengine_2017-12-12_19-24-07](https://user-images.githubusercontent.com/4485172/33911753-1166edbe-df72-11e7-81f4-a2aff5576d90.png)
![game_2017-12-12_19-22-09](https://user-images.githubusercontent.com/4485172/33911649-c944d71c-df71-11e7-941a-4b7ed4ea30c0.png)

Also, here's the map's file, just in case:
[002.zip](https://github.com/M3rein/Pokemon-MK/files/1553494/002.zip)

**EDIT**: I was bored and made another attempt, same result.
![pokemonengine_2017-12-12_21-11-12](https://user-images.githubusercontent.com/4485172/33915288-43acb1a0-df81-11e7-8c98-109e4f25d160.png)

**Comment by M3rein** [comment]
Rather than dividing by width to determine a tile's y placement, it was using the height of the map. That's why, after **9** tiles in the map in you attached, it goes one tile down. Fixed by changing a `@height` to a `@width` in the formula.
